steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.studio-analysis-worker
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/studio-analysis/worker:$BUILD_ID
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/studio-analysis/worker:$BUILD_ID
