const frontendTransformAllowList = [
    "react-markdown",
    "remark-parse",
    "remark-rehype",
    "unified",
    "bail",
    "trough",
    "vfile",
    "vfile-message",
    "micromark",
    "micromark-core-commonmark",
    "micromark-factory-destination",
    "micromark-factory-label",
    "micromark-factory-space",
    "micromark-factory-title",
    "micromark-factory-whitespace",
    "micromark-util-character",
    "micromark-util-chunked",
    "micromark-util-classify-character",
    "micromark-util-combine-extensions",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-encode",
    "micromark-util-html-tag-name",
    "micromark-util-normalize-identifier",
    "micromark-util-resolve-all",
    "micromark-util-sanitize-uri",
    "micromark-util-subtokenize",
    "micromark-util-symbol",
    "micromark-util-types",
    "decode-named-character-reference",
    "character-entities",
    "character-entities-html4",
    "character-entities-legacy",
    "mdast-util-from-markdown",
    "mdast-util-to-hast",
    "mdast-util-to-string",
    "mdast-util-definitions",
    "mdast-util-phrasing",
    "mdast-util-gfm",
    "mdast-util-gfm-autolink-literal",
    "mdast-util-gfm-footnote",
    "mdast-util-gfm-strikethrough",
    "mdast-util-gfm-table",
    "mdast-util-gfm-task-list-item",
    "hast-util-to-jsx-runtime",
    "hast-util-whitespace",
    "hast-util-to-estree",
    "hast-util-raw",
    "hast-util-from-html",
    "hast-util-parse-selector",
    "hast-util-embedded",
    "property-information",
    "space-separated-tokens",
    "comma-separated-tokens",
    "unist-util-visit",
    "unist-util-visit-parents",
    "unist-util-position",
    "unist-util-stringify-position",
    "unist-util-is",
    "unist-util-generated",
    "devlop",
    "is-plain-obj",
    "zwitch"
].join("|");

module.exports = {
  projects: [
    {
      displayName: "server",
      testEnvironment: "node",
      // Keep jest-focused tests only; exclude legacy Node-style scripts in test/ top-level
      testMatch: [
        "<rootDir>/src/**/__tests__/**",
        "<rootDir>/src/**/*.test.js",
        "<rootDir>/test/**/__tests__/**",
        "<rootDir>/test/**/*.jest.test.js",
        "<rootDir>/test/paypal-subscription.routes.test.js",
        "<rootDir>/test/payments-routes.test.js",
        "<rootDir>/test/payments.dev.mock.subscription.test.js",
      ],
      // Load early env setup before any modules are imported to ensure bypass flags are present
      setupFiles: ["<rootDir>/test/jest.setup.js"],
      setupFilesAfterEnv: ["<rootDir>/test/jest.setup.js"],
      transform: {
        "^.+\\.[tj]sx?$": "babel-jest",
      },
      transformIgnorePatterns: ["/node_modules/"],
      testTimeout: 20000,
    },
    {
      displayName: "frontend",
      // Use node environment unless jest-environment-jsdom is available; this avoids validation errors during CI.
      testEnvironment: process.env.JEST_FORCE_NODE_ENV === "1" ? "node" : "jsdom",
      testMatch: ["<rootDir>/frontend/src/**/__tests__/**"],
      setupFilesAfterEnv: ["<rootDir>/frontend/src/setupTests.js"],
      moduleNameMapper: {
        "\\.(css|less|scss|sass)$": "<rootDir>/test/__mocks__/styleMock.js",
        "\\.(gif|ttf|eot|svg|png|jpg|jpeg)$": "<rootDir>/test/__mocks__/fileMock.js",
        "^react-markdown$": "<rootDir>/test/__mocks__/reactMarkdownMock.js",
      },
      transform: {
        "^.+\\.[tj]sx?$": "babel-jest",
      },
      testTimeout: 20000,
      transformIgnorePatterns: [`/node_modules/(?!(${frontendTransformAllowList})/)`],
    },
  ],
  // Global config used when running top-level tests
  testPathIgnorePatterns: ["test/e2e/playwright/"],
  verbose: true,
};
