@echo off
echo Starting Python Media Worker for AI Clip Generation...
cd python_media_worker
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Service...
python main_media_server.py
pause